---
- name: Restart a container
  hosts: all
  tasks:

  - name: Ensure ssh host key known
    delegate_to: localhost
    lineinfile:
      dest: ~/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -trsa -p 22' + ' ' + inventory_hostname) }}"

  - name: Setup gcloud docker
    ansible.builtin.command: gcloud auth configure-docker europe-west2-docker.pkg.dev
    register: result
    changed_when: "'gcloud credential helpers already registered correctly' not in result.stderr"

  - name: Copy environment file
    become: yes
    ansible.builtin.copy:
      src: "{{lookup('ansible.builtin.env', 'GITHUB_WORKSPACE')}}/ckan/.env.server"
      dest: "/ckan/env"

  - name: "Redeploy CKAN container"
    community.docker.docker_container:
      name: ckan-gla
      image: 'europe-west2-docker.pkg.dev/gla-evaluation-magda/swirrl-london-datastore-ckan/ckan-gla:latest'
      pull: true
      state: started
      restart: true
      env_file: /ckan/env
      env:
        CKAN_SITE_URL: "http://{{ lookup('ansible.builtin.env', 'CKAN_SITE_IP', default='ckan') }}"
      ports: 
        - "5000:5000"

