---
- name: Restart a container
  hosts: all
  tasks:
  - name: Setup gcloud docker
    ansible.builtin.command: gcloud auth configure-docker europe-west2-docker.pkg.dev

  - name: "Redeploy CKAN container"
    community.docker.docker_container:
      name: ckan-gla
      image: 'europe-west2-docker.pkg.dev/gla-evaluation-magda/swirrl-london-datastore-ckan/ckan-gla:latest'
      pull: true
      state: started
      restart: true
      env_file: /ckan/env
      ports: 
        - "5000:5000"

