name: deploy-ckan

on: workflow_dispatch

env:
  GCP_AUTH_KIND: serviceaccount

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      - name: 'Build image'
        run: ./build-image.sh

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Configure docker'
        run: |-
          gcloud auth configure-docker europe-west2-docker.pkg.dev

      - name: 'Tag and push image'
        run: |-
          docker tag ckan-gla:ckan-2.10 europe-west2-docker.pkg.dev/gla-evaluation-magda/swirrl-london-datastore-ckan/ckan-gla:latest
          docker push europe-west2-docker.pkg.dev/gla-evaluation-magda/swirrl-london-datastore-ckan/ckan-gla:latest

      - name: 'Install google auth'
        run: |-
          pip install ansible requests google-auth
          ansible-galaxy collection install google.cloud

      #- name: 'Decrypt Private Key'
        #run: |-
          #mkdir -p $HOME/secrets
          #gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/ansible-key ansible-key.gpg
        #working-directory: deploy/ansible
        #env:
          #PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          GCP_SERVICE_ACCOUNT_CONTENTS: '${{ secrets.GCLOUD_SERVICE_KEY }}'
        with:
          playbook: deploy-ckan.yml
          directory: ./deploy/ansible
          key: ${{secrets.ANSIBLE_KEY}}
          known_hosts: ${{secrets.KNOWN_HOSTS}}
          options: |
            --inventory ckan_dev.gcp.yml
            --user ${{ secrets.ANSIBLE_USER }}
            --verbose

      #- name: 'Restart docker container'
        #working-directory: deploy/ansible
        #env:
          #GCP_SERVICE_ACCOUNT_CONTENTS: '${{ secrets.GCLOUD_SERVICE_KEY }}'
        #run:  ansible-playbook -i ckan_dev.gcp.yml --private-key $HOME/secrets/ansible-key deploy-ckan.yml
